CREATE OR REPLACE DIRECTORY INVOICE_DIR AS 'C:\Users\zelih\OneDrive\Masaüstü';


CREATE OR REPLACE TABLE INVOICE_EXTERNAL (
    MSISDN VARCHAR2(20),
    SERVICE_NAME VARCHAR2(100),
    START_DATE VARCHAR2(10),
    END_DATE VARCHAR2(10),
    PRODUCT_TYPE VARCHAR2(10),
    NET_AMOUNT NUMBER
) ORGANIZATION EXTERNAL (
    TYPE ORACLE_LOADER
    DEFAULT DIRECTORY INVOICE_DIR
    ACCESS PARAMETERS (
        RECORDS DELIMITED BY NEWLINE
        FIELDS TERMINATED BY '|'
    )
    LOCATION ('invoice_230917.txt')
);


SELECT * FROM INVOICE_EXTERNAL;